### ISSUE TITLE
can't install using homebrew

### ISSUE THREAD

**Issue by halpz** [yt-dlp/homebrew-taps#2]
can't install using home-brew

```
% brew install yt-dlp/taps/yt-dlp
==> Downloading https://files.pythonhosted.org/packages/f0/82/b4dc507e050a24d1c1a15af4e9ebe01fc17f36e2de4d2ee857afd31b21
Already downloaded: /Users/paul/Library/Caches/Homebrew/downloads/7fff74395706064faab6aa3dd7579a881df6d1c01bdb3de251f89ddbba05a66a--yt-dlp-2022.3.8.1.tar.gz
==> Installing yt-dlp from yt-dlp/taps
==> python3.9 -m venv --system-site-packages /opt/homebrew/Cellar/yt-dlp/2022.3.8.1/libexec
==> /opt/homebrew/Cellar/yt-dlp/2022.3.8.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /pr
Last 15 lines from /Users/paul/Library/Logs/Homebrew/yt-dlp/02.pip:

Using pip 21.3.1 from /opt/homebrew/Cellar/yt-dlp/2022.3.8.1/libexec/lib/python3.9/site-packages/pip (python 3.9)
Processing /private/tmp/yt-dlp-20220308-35460-pghbrq/yt-dlp-2022.3.8.1
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/tmp/yt-dlp-20220308-35460-pghbrq/yt-dlp-2022.3.8.1/setup.py", line 26, in <module>
      REQUIREMENTS = open('requirements.txt', encoding='utf-8').read().splitlines()
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  Preparing metadata (setup.py): finished with status 'error'
WARNING: Discarding file:///private/tmp/yt-dlp-20220308-35460-pghbrq/yt-dlp-2022.3.8.1. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/opt/homebrew/Cellar/yt-dlp/2022.3.8.1/libexec/bin/python3.9 -m pip install --upgrade pip' command.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/yt-dlp/homebrew-taps/issues

```

**Comment by rouge8** [comment]
Same error when updating

**Comment by pukkandan** [comment]
@Lesmiscore any idea how to fix this?

**Comment by Lesmiscore** [comment]
```
$ pip install -v --no-deps --no-binary :all: --ignore-installed https://files.pythonhosted.org/packages/f0/82/b4dc507e050a24d1c1a15af4e9ebe01fc17f36e2de4d2ee857afd31b21c4/yt-dlp-2022.3.8.1.tar.gz
Using pip 21.3.1 from /home/lesmi/tmp/testvenv/lib/python3.9/site-packages/pip (python 3.9)
Collecting https://files.pythonhosted.org/packages/f0/82/b4dc507e050a24d1c1a15af4e9ebe01fc17f36e2de4d2ee857afd31b21c4/yt-dlp-2022.3.8.1.tar.gz
  Downloading yt-dlp-2022.3.8.1.tar.gz (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s            
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-vte0tt87/setup.py", line 26, in <module>
      REQUIREMENTS = open('requirements.txt', encoding='utf-8').read().splitlines()
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  Preparing metadata (setup.py) ... error
WARNING: Discarding https://files.pythonhosted.org/packages/f0/82/b4dc507e050a24d1c1a15af4e9ebe01fc17f36e2de4d2ee857afd31b21c4/yt-dlp-2022.3.8.1.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/home/lesmi/tmp/testvenv/bin/python3.9 -m pip install --upgrade pip' command.
```
Just specifying tarball URL doesn't install!
ref: https://github.com/yt-dlp/yt-dlp/commit/08d30158ec8e7e08c1d83dcfde6dba18c95b2640

**Comment by pukkandan** [comment]
Will be fixed when https://github.com/yt-dlp/yt-dlp/issues/2995 is

**Comment by pukkandan** [comment]
@Lesmiscore Could you update the formulae to https://pypi.org/project/yt-dlp/2022.3.8.2/

**Comment by Lesmiscore** [comment]
```
$ brew upgrade yt-dlp/taps/yt-dlp
==> Upgrading 1 outdated package:
yt-dlp/taps/yt-dlp 2022.2.4 -> 2022.3.8.2
==> Downloading https://files.pythonhosted.org/packages/1b/a9/781ef55dd51d331e3d8ca60723853f13e75be5b8713870c015b3c4283326/yt-dlp-2022.3.8.2.tar.gz
######################################################################## 100.0%
==> Upgrading yt-dlp/taps/yt-dlp
  2022.2.4 -> 2022.3.8.2 

==> python3.9 -m venv --system-site-packages /home/linuxbrew/.linuxbrew/Cellar/yt-dlp/2022.3.8.2/libexec
==> /home/linuxbrew/.linuxbrew/Cellar/yt-dlp/2022.3.8.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/yt-dlp-20220309-
==> Caveats
Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/yt-dlp/2022.3.8.2: 3,099 files, 28.1MB, built in 10 seconds
==> Running `brew cleanup yt-dlp`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /home/linuxbrew/.linuxbrew/Cellar/yt-dlp/2022.2.4... (3,082 files, 27.6MB)
Removing: /home/lesmi/.cache/Homebrew/yt-dlp--2022.3.8.1.tar.gz... (2.1MB)
```
Confirmed 2022.03.08.2 can be installed via Homebrew.
