### ISSUE TITLE
No such file or directory: 'requirements.txt' when upgrading from 2022.2.4 to 2022.3.8.1 

### ISSUE THREAD

**Issue by anta40** [yt-dlp/homebrew-taps#3]
Just happened when running `brew upgrade`
```
==> Upgrading 1 outdated package:
yt-dlp/taps/yt-dlp 2022.2.4 -> 2022.3.8.1
==> Downloading https://files.pythonhosted.org/packages/f0/82/b4dc507e050a24d1c1a15af4e9ebe01fc17f36e2de4d2ee857afd31b21c4/yt-dlp-2022.3.8.1.t
Already downloaded: /Users/andre/Library/Caches/Homebrew/downloads/7fff74395706064faab6aa3dd7579a881df6d1c01bdb3de251f89ddbba05a66a--yt-dlp-2022.3.8.1.tar.gz
```

The error is:
```
==> python3.9 -m venv --system-site-packages /usr/local/Cellar/yt-dlp/2022.3.8.1/libexec
==> /usr/local/Cellar/yt-dlp/2022.3.8.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/yt-dlp-20220309
Last 15 lines from /Users/andre/Library/Logs/Homebrew/yt-dlp/02.pip:

Using pip 21.3.1 from /usr/local/Cellar/yt-dlp/2022.3.8.1/libexec/lib/python3.9/site-packages/pip (python 3.9)
Processing /private/tmp/yt-dlp-20220309-5521-1gqta34/yt-dlp-2022.3.8.1
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/tmp/yt-dlp-20220309-5521-1gqta34/yt-dlp-2022.3.8.1/setup.py", line 26, in <module>
      REQUIREMENTS = open('requirements.txt', encoding='utf-8').read().splitlines()
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  Preparing metadata (setup.py): finished with status 'error'
WARNING: Discarding file:///private/tmp/yt-dlp-20220309-5521-1gqta34/yt-dlp-2022.3.8.1. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/Cellar/yt-dlp/2022.3.8.1/libexec/bin/python3.9 -m pip install --upgrade pip' command.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/yt-dlp/homebrew-taps/issues
```

I tried upgrading pip manually by calling `python3.9 -m pip install --upgrade pip`, and eventually the error message already described above still appears.

I'm on MacOS Big Sur, BTW.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/homebrew-taps/issues/2
